### ISSUE TITLE
node setup TensorFlow : issue on Apple M1 / Silicon during dependencies installation

### ISSUE THREAD

**Issue by superharoun** [Superalgos/Superalgos#1752]
## Context

**Operating System:** MacOs

**Software version:** today's master branch

**Workspace version:** N/A

**Reproducible:** the issue may be reproduced.

### 1. Explain what the problem seems to be.

When running node setup tensorflow, got the following message : 
`Installing node dependencies at the following directories:

[
  '/Users/xxx/Superalgos/Projects/TensorFlow/TS/Bot-Modules/Learning-Bot/Low-Frequency-Learning'
]

There was an error installing some dependencies error: 

Error: Command failed: echo Results of install at /Users/xxx/Superalgos/Projects/TensorFlow/TS/Bot-Modules/Learning-Bot/Low-Frequency-Learning & npm ci
npm ERR! code 1
npm ERR! path /Users/xxx/Superalgos/Projects/TensorFlow/TS/Bot-Modules/Learning-Bot/Low-Frequency-Learning/node_modules/@tensorflow/tfjs-node
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! CPU-darwin-3.8.0.tar.gz
npm ERR! * Downloading libtensorflow
npm ERR! /Users/xxx/Superalgos/Projects/TensorFlow/TS/Bot-Modules/Learning-Bot/Low-Frequency-Learning/node_modules/@tensorflow/tfjs-node/scripts/install.js:103
npm ERR!     throw new Error(`Unsupported system: ${libType}-${platform}-${os.arch()}`);
npm ERR!           ^
npm ERR! 
npm ERR! Error: Unsupported system: cpu-darwin-arm64
npm ERR!     at getPlatformLibtensorflowUri (/Users/haroun/SpecialOps/Superalgos/Projects/TensorFlow/TS/Bot-Modules/Learning-Bot/Low-Frequency-Learning/node_modules/@tensorflow/tfjs-node/scripts/install.js:103:11)
npm ERR!     at downloadLibtensorflow (/Users/haroun/SpecialOps/Superalgos/Projects/TensorFlow/TS/Bot-Modules/Learning-Bot/Low-Frequency-Learning/node_modules/@tensorflow/tfjs-node/scripts/install.js:136:15)
npm ERR!     at async run (/Users/haroun/SpecialOps/Superalgos/Projects/TensorFlow/TS/Bot-Modules/Learning-Bot/Low-Frequency-Learning/node_modules/@tensorflow/tfjs-node/scripts/install.js:205:5)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2021-09-13T19_57_47_177Z-debug.log

    at ChildProcess.exithandler (node:child_process:326:12)
    at ChildProcess.emit (node:events:369:20)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'echo Results of install at /Users/xxx/Superalgos/Projects/TensorFlow/TS/Bot-Modules/Learning-Bot/Low-Frequency-Learning & npm ci'
}
`

### 2. Clearly explain what you wish to accomplish.

Installing SA with TensorFlow dependencies on Apple M1 / Silicon. 
Without TensorFlow it worked.

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

See 1.

### 4. Explain what is the result you expect from your actions.

How can installation finish by itself ?

### 5. Explain what happens instead of the expected results.

Get error from point 1.

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

See point 1.

## Attach a video reproducing the issue

N/A

## Attach relevant log files and error screenshots

Are the logs above sufficient ?

## Attach you custom workspace if any

N/A

**Comment by harrellbm** [comment]
@PLuv
