### ISSUE TITLE
Improve error handling while fetching Exchange Raw Data

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [Superalgos/Superalgos#197]
Here it happened that 95% of the data was fetched, then the exchange became unavailable for a while, and then the fetching started all over again from the begining.

 It should have saved the already fetched data.

```
020-04-07T07:19:39.362Z              Binance   ETH/USDT    Exchange-Raw-Data                Historic-OHLCVs      Internal Loop #     1294                     2020-02-05    93.57 %
*********** ['2020-04-07T07:19:50.368Z',6628,'User Bot','[ERROR] start -> getOHLCVs -> Retrying Later -> err = ExchangeNotAvailable: binance GET https://api.binance.com/api/v3/klines?symbol=ETHUSDT&interval=1m&startTime=1580878920000&limit=1000 system request to https://api.binance.com/api/v3/klines?symbol=ETHUSDT&interval=1m&startTime=1580878920000&limit=1000 failed, reason: read ECONNRESET
    at c:\Superalgos\TaskServer\node_modules\ccxt\js\base\Exchange.js:390:35
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async timeout (c:\Superalgos\TaskServer\node_modules\ccxt\js\base\functions\time.js:178:24)
    at async binance.request (c:\Superalgos\TaskServer\node_modules\ccxt\js\binance.js:1954:26)
    at async binance.fetchOHLCV (c:\Superalgos\TaskServer\node_modules\ccxt\js\binance.js:763:26)
    at async getOHLCVs (eval at onBotDownloaded (c:\Superalgos\TaskServer\SensorBotProcessMainLoop.js:61:50), <anonymous>:278:40)
    at async begin (eval at onBotDownloaded (c:\Superalgos\TaskServer\SensorBotProcessMainLoop.js:61:50), <anonymous>:140:17)'] @ Masters-Exchange-Raw-Data-Historic-OHLCVs
2020-04-07T07:20:00.381Z              Binance   ETH/USDT    Exchange-Raw-Data                Historic-OHLCVs      Main Loop     #        2
2020-04-07T07:20:18.982Z              Binance   ETH/USDT    Exchange-Raw-Data                Historic-OHLCVs      Internal Loop #        0                     2015-01-01     0.00 %
*********** ['2020-04-07T07:20:30.538Z',158,'User Bot','[ERROR] start -> getOHLCVs -> Retrying Later -> err = ExchangeNotAvailable: binance GET https://api.binance.com/api/v3/exchangeInfo system request to https://api.binance.com/api/v3/exchangeInfo failed, reason: getaddrinfo ENOTFOUND api.binance.com
    at c:\Superalgos\TaskServer\node_modules\ccxt\js\base\Exchange.js:390:35
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async timeout (c:\Superalgos\TaskServer\node_modules\ccxt\js\base\functions\time.js:178:24)
    at async binance.request (c:\Superalgos\TaskServer\node_modules\ccxt\js\binance.js:1954:26)
    at async binance.fetchMarkets (c:\Superalgos\TaskServer\node_modules\ccxt\js\binance.js:352:26)
    at async binance.loadMarketsHelper (c:\Superalgos\TaskServer\node_modules\ccxt\js\base\Exchange.js:690:25)
    at async binance.fetchOHLCV (c:\Superalgos\TaskServer\node_modules\ccxt\js\binance.js:750:9)
    at async getOHLCVs (eval at onBotDownloaded (c:\Superalgos\TaskServer\SensorBotProcessMainLoop.js:61:50), <anonymous>:278:40)
    at async begin (eval at onBotDownloaded (c:\Superalgos\TaskServer\SensorBotProcessMainLoop.js:61:50), <anonymous>:140:17)'] @ Masters-Exchange-Raw-Data-Historic-OHLCVs
2020-04-07T07:20:40.540Z              Binance   ETH/USDT    Exchange-Raw-Data                Historic-OHLCVs      Main Loop     #        3
2020-04-07T07:20:59.137Z              Binance   ETH/USDT    Exchange-Raw-Data                Historic-OHLCVs      Internal Loop #        0                     2015-01-01     0.00 %
*********** ['2020-04-07T07:21:10.690Z',158,'User Bot','[ERROR] start -> getOHLCVs -> Retrying Later -> err = ExchangeNotAvailable: binance GET https://api.binance.com/api/v3/exchangeInfo system request to https://api.binance.com/api/v3/exchangeInfo failed, reason: getaddrinfo ENOTFOUND api.binance.com
    at c:\Superalgos\TaskServer\node_modules\ccxt\js\base\Exchange.js:390:35
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async timeout (c:\Superalgos\TaskServer\node_modules\ccxt\js\base\functions\time.js:178:24)
    at async binance.request (c:\Superalgos\TaskServer\node_modules\ccxt\js\binance.js:1954:26)
    at async binance.fetchMarkets (c:\Superalgos\TaskServer\node_modules\ccxt\js\binance.js:352:26)

 
at async binance.loadMarketsHelper (c:\Superalgos\TaskServer\node_modules\ccxt\js\base\Exchange.js:690:25)
    at async binance.fetchOHLCV (c:\Superalgos\TaskServer\node_modules\ccxt\js\binance.js:750:9)
    at async getOHLCVs (eval at onBotDownloaded (c:\Superalgos\TaskServer\SensorBotProcessMainLoop.js:61:50), <anonymous>:278:40)
    at async begin (eval at onBotDownloaded (c:\Superalgos\TaskServer\SensorBotProcessMainLoop.js:61:50), <anonymous>:140:17)'] @ Masters-Exchange-Raw-Data-Historic-OHLCVs
2020-04-07T07:21:20.692Z              Binance   ETH/USDT    Exchange-Raw-Data                Historic-OHLCVs      Main Loop     #        4
2020-04-07T07:21:39.314Z              Binance   ETH/USDT    Exchange-Raw-Data                Historic-OHLCVs      Internal Loop #        0                     2015-01-01     0.00 %
2020-04-07T07:21:41.680Z              Binance   ETH/USDT    Exchange-Raw-Data                Historic-OHLCVs      Internal Loop #        1                     2017-08-17     0.00 %
2020-04-07T07:21:42.737Z              Binance   ETH/USDT    Exchange-Raw-Data                Historic-OHLCVs      Internal Loop #        2                     2017-08-18     0.10 %
2020-04-07T07:21:43.539Z              Binance   ETH/USDT    Exchange-Raw-Data                Historic-OHLCVs      Internal Loop #        3                     2017-08-19     0.21 %
2020-04-07T07:21:44.433Z              Binance   ETH/USDT    Exchange-Raw-Data                Historic-OHLCVs      Internal Loop #        4                     2017-08-19     0.21 %
2020-04-07T07:21:45.337Z              Binance   ETH/USDT    Exchange-Raw-Data                Historic-OHLCVs      Internal Loop #        5                     2017-08-20     0.31 %

```

**Comment by Luis-Fernando-Molina** [comment]
done
