### ISSUE TITLE
Multiple Paper Trading Sessions 

### ISSUE THREAD

**Issue by Shaifff** [Superalgos/Superalgos#237]
Objective: Run a paper trading session on both WHB V2 and BBTB simultaneously

Error:

`
*********** ['2020-05-24T20:44:08.485Z',3393,'Trading Bot','[ERROR] start -> writeDailyFiles -> writeSnapshotFile -> err = TypeError: Cannot read property 'length' of undefined
    at parseRecord (/Users/xxx/Downloads/Superalgos-develop/Superalgos-develop/TaskServer/TradingBot.js:980:56)
    at writeSnapshotFile (/Users/xxx/Downloads/Superalgos-develop/Superalgos-develop/TaskServer/TradingBot.js:971:25)
    at writeSnapshotFiles (/Users/xxx/Downloads/Superalgos-develop/Superalgos-develop/TaskServer/TradingBot.js:949:21)
    at onFileCreated (/Users/xxx/Downloads/Superalgos-develop/Superalgos-develop/TaskServer/TradingBot.js:932:33)
    at onTempRenamed (/Users/xxx/Downloads/Superalgos-develop/Superalgos-develop/TaskServer/FileStorage.js:315:41)
    at FSReqCallback.oncomplete (fs.js:159:23)'] @ TradingEngines-Protocol-Engine-Multi-Period
*********** ['2020-05-24T20:44:08.485Z',3396,'Trading Process Main Loop','[ERROR] run -> loop -> startProcessFramework -> onFinished -> Operation Failed. Aborting the process.'] @ TradingEngines-Protocol-Engine-Multi-Period
*********** ['2020-05-24T20:44:08.487Z',6,'Root','[ERROR] start -> bootingBot -> runTradingBot -> onInitializeReady -> whenStartFinishes -> err = Operation Failed'] @ TradingEngines-Protocol-Engine-Multi-Period
*********** ['2020-05-24T20:44:08.487Z',7,'Root','[ERROR] start -> bootingBot -> runTradingBot -> onInitializeReady -> whenStartFinishes -> Execution will be stopped. '] @ TradingEngines-Protocol-Engine-Multi-Period
*********** ['2020-05-24T20:44:08.487Z',8,'Root','[ERROR] start -> bootingBot -> runTradingBot -> onInitializeReady -> whenStartFinishes -> Bye.'] @ TradingEngines-Protocol-Engine-Multi-Period
*********** ['2020-05-24T20:44:08.487Z',9,'Root','[ERROR] start -> bootingBot -> runTradingBot -> onInitializeReady -> whenStartFinishes -> Bot Id = TradingEngines.Protocol-Engine.Multi-Period'] @ TradingEngines-Protocol-Engine-Multi-Period
Task Server                                              Root : [ERROR] start -> bootingBot -> runTradingBot -> onInitializeReady -> whenStartFinishes -> Bot execution finished with errors. Please check the logs.
Failed to process updates. TelegramError: 409: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
    at /Users/xxx/Downloads/Superalgos-develop/Superalgos-develop/TaskServer/node_modules/telegraf/core/network/client.js:281:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 409,
  response: {
    ok: false,
    error_code: 409,
    description: 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'
  },
  description: 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',
  parameters: {},
  on: { method: 'getUpdates?offset=0&limit=100&timeout=30', payload: {} }
}
2020-05-24T20:44:13.356Z              Binance   BTC/USDT                Protocol-Engine                   Multi-Period      Main Loop     #        2 Paper Trading Session Paper WHB
2020-05-24T20:44:25.365Z              Bittrex   BTC/USDT                       Webhooks                  Check-Webhook      Main Loop     #      584
2020-05-24T20:44:25.423Z             Bitfinex   BTC/USDT                       Webhooks                  Check-Webhook      Main Loop     #      584
2020-05-24T20:44:25.432Z              Bittrex   ETH/USDT                       Webhooks                  Check-Webhook      Main Loop     #      584
*********** ['2020-05-24T20:44:32.726Z',3371,'Trading Bot','[ERROR] start -> writeDailyFiles -> writeSnapshotFile -> err = TypeError: Cannot read property 'length' of undefined
    at parseRecord (/Users/xxx/Downloads/Superalgos-develop/Superalgos-develop/TaskServer/TradingBot.js:980:56)
    at writeSnapshotFile (/Users/xxx/Downloads/Superalgos-develop/Superalgos-develop/TaskServer/TradingBot.js:971:25)
    at writeSnapshotFiles (/Users/xxx/Downloads/Superalgos-develop/Superalgos-develop/TaskServer/TradingBot.js:949:21)
    at onFileCreated (/Users/xxx/Downloads/Superalgos-develop/Superalgos-develop/TaskServer/TradingBot.js:932:33)
    at onTempRenamed (/Users/xxx/Downloads/Superalgos-develop/Superalgos-develop/TaskServer/FileStorage.js:315:41)
    at FSReqCallback.oncomplete (fs.js:159:23)'] @ TradingEngines-Protocol-Engine-Multi-Period
*********** ['2020-05-24T20:44:32.728Z',3374,'Trading Process Main Loop','[ERROR] run -> loop -> startProcessFramework -> onFinished -> Operation Failed. Aborting the process.'] @ TradingEngines-Protocol-Engine-Multi-Period
*********** ['2020-05-24T20:44:32.730Z',6,'Root','[ERROR] start -> bootingBot -> runTradingBot -> onInitializeReady -> whenStartFinishes -> err = Operation Failed'] @ TradingEngines-Protocol-Engine-Multi-Period
*********** ['2020-05-24T20:44:32.730Z',7,'Root','[ERROR] start -> bootingBot -> runTradingBot -> onInitializeReady -> whenStartFinishes -> Execution will be stopped. '] @ TradingEngines-Protocol-Engine-Multi-Period
*********** ['2020-05-24T20:44:32.730Z',8,'Root','[ERROR] start -> bootingBot -> runTradingBot -> onInitializeReady -> whenStartFinishes -> Bye.'] @ TradingEngines-Protocol-Engine-Multi-Period
*********** ['2020-05-24T20:44:32.730Z',9,'Root','[ERROR] start -> bootingBot -> runTradingBot -> onInitializeReady -> whenStartFinishes -> Bot Id = TradingEngines.Protocol-Engine.Multi-Period'] @ TradingEngines-Protocol-Engine-Multi-Period
Task Server                                              Root : [ERROR] start -> bootingBot -> runTradingBot -> onInitializeReady -> whenStartFinishes -> Bot execution finished with errors. Please check the logs.
` 

How to recreate error:
1) Run paper trading task in the network node for either WHB or BBTB
2) Run the paper trading session for the same system
3) Run the paper trading task for the other trading system
4) Run the paper trading task for the second trading system from step 3

**Comment by Luis-Fernando-Molina** [comment]
This is fixed at Beta 5 version at the develop branch
