### ISSUE TITLE
Console Error during Live Trade BBTB

### ISSUE THREAD

**Issue by EduRemix** [Superalgos/Superalgos#266]
## Before you open an issue

There are two requirements to open an issue:

1. You must first follow the [Troubleshooting Guide](https://docs.superalgos.org/suite-how-to-troubleshoot-an-issue.html)

2. If your issue hasn't been resolved by following the Troubleshooting Guide, then follow the guide on [How to Report an Issue](https://docs.superalgos.org/suite-how-to-report-an-issue.html).

## Context

*Complete and adjust the contents leaving the information that fits your case and deleting the information that doesn't.*

**Operating System:** Linux Ubuntu 18.04 xfce

**Software version:** today's master branch 

**Workspace version:**  Workspace - Binance - WHB - BBTB.json 

**Reproducible:**  may not be reproduced.

### 1. Explain what the problem seems to be.

An error appeared on the console during a live trade

### 2. Clearly explain what you wish to accomplish.

N/A

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

The program runs in live trade with BBTB.

### 4. Explain what is the result you expect from your actions.

N/A

### 5. Explain what happens instead of the expected results.

N/A

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

2020-06-14T06:08:01.081Z              Binance   BTC/USDT              Exchange-Raw-Data                Historic-OHLCVs      Main Loop     #     6192
2020-06-14T06:08:05.189Z              Binance   BTC/USDT                Candles-Volumes             Multi-Period-Daily      Main Loop     #     6190
2020-06-14T06:08:05.488Z              Binance   BTC/USDT                Candles-Volumes            Multi-Period-Market      Main Loop     #     6186
*********** ['2020-06-14T06:08:10.860Z',52,'Indicator Process Main Loop','[ERROR] run -> loop -> finishProcessExecutionEvents -> err = TypeError: Cannot read property 'finish' of undefined
    at finishProcessExecutionEvents (/home/cloudsigma/Downloads/Superalgos-master-5/TaskServer/IndicatorBotProcessMainLoop.js:889:52)
    at onFinished (/home/cloudsigma/Downloads/Superalgos-master-5/TaskServer/IndicatorBotProcessMainLoop.js:607:45)
    at advanceTime (eval at onBotDownloaded (/home/cloudsigma/Downloads/Superalgos-master-5/TaskServer/IndicatorBotProcessMainLoop.js:62:46), <anonymous>:255:29)
    at Object.raiseEvents (/home/cloudsigma/Downloads/Superalgos-master-5/TaskServer/ProcessOutput.js:95:13)
    at onFileCreated (/home/cloudsigma/Downloads/Superalgos-master-5/TaskServer/StatusReport.js:344:31)
    at onTempRenamed (/home/cloudsigma/Downloads/Superalgos-master-5/TaskServer/FileStorage.js:282:45)
    at FSReqWrap.oncomplete (fs.js:135:15)'] @ Masters-Candles-Volumes-Multi-Period-Daily
*********** ['2020-06-14T06:08:10.863Z',131,'Root','[ERROR] start -> bootingBot -> runIndicatorBot -> onInitializeReady -> whenStartFinishes -> err = Cannot read property 'finish' of undefined'] @ Masters-Candles-Volumes-Multi-Period-Daily
*********** ['2020-06-14T06:08:10.863Z',132,'Root','[ERROR] start -> bootingBot -> runIndicatorBot -> onInitializeReady -> whenStartFinishes -> Execution will be stopped. '] @ Masters-Candles-Volumes-Multi-Period-Daily
*********** ['2020-06-14T06:08:10.863Z',133,'Root','[ERROR] start -> bootingBot -> runIndicatorBot -> onInitializeReady -> whenStartFinishes -> Bye.'] @ Masters-Candles-Volumes-Multi-Period-Daily
*********** ['2020-06-14T06:08:10.863Z',134,'Root','[ERROR] start -> bootingBot -> runIndicatorBot -> onInitializeReady -> whenStartFinishes -> Bot Id = Masters.Candles-Volumes.Multi-Period-Daily'] @ Masters-Candles-Volumes-Multi-Period-Daily
Task Server                                              Root : [ERROR] start -> bootingBot -> runIndicatorBot -> onInitializeReady -> whenStartFinishes -> Bot execution finished with errors. Please check the logs.
*********** ['2020-06-14T06:08:15.272Z',18,'Indicator Process Main Loop','[ERROR] run -> loop -> finishProcessExecutionEvents -> err = TypeError: Cannot read property 'finish' of undefined
    at finishProcessExecutionEvents (/home/cloudsigma/Downloads/Superalgos-master-5/TaskServer/IndicatorBotProcessMainLoop.js:889:52)
    at onFinished (/home/cloudsigma/Downloads/Superalgos-master-5/TaskServer/IndicatorBotProcessMainLoop.js:607:45)
    at advanceTime (eval at onBotDownloaded (/home/cloudsigma/Downloads/Superalgos-master-5/TaskServer/IndicatorBotProcessMainLoop.js:62:46), <anonymous>:421:29)
    at Object.raiseEvents (/home/cloudsigma/Downloads/Superalgos-master-5/TaskServer/ProcessOutput.js:95:13)
    at onFileCreated (/home/cloudsigma/Downloads/Superalgos-master-5/TaskServer/StatusReport.js:344:31)
    at onTempRenamed (/home/cloudsigma/Downloads/Superalgos-master-5/TaskServer/FileStorage.js:282:45)
    at FSReqWrap.oncomplete (fs.js:135:15)'] @ Masters-Candles-Volumes-Multi-Period-Market
*********** ['2020-06-14T06:08:15.273Z',131,'Root','[ERROR] start -> bootingBot -> runIndicatorBot -> onInitializeReady -> whenStartFinishes -> err = Cannot read property 'finish' of undefined'] @ Masters-Candles-Volumes-Multi-Period-Market
*********** ['2020-06-14T06:08:15.274Z',132,'Root','[ERROR] start -> bootingBot -> runIndicatorBot -> onInitializeReady -> whenStartFinishes -> Execution will be stopped. '] @ Masters-Candles-Volumes-Multi-Period-Market
*********** ['2020-06-14T06:08:15.274Z',133,'Root','[ERROR] start -> bootingBot -> runIndicatorBot -> onInitializeReady -> whenStartFinishes -> Bye.'] @ Masters-Candles-Volumes-Multi-Period-Market
*********** ['2020-06-14T06:08:15.274Z',134,'Root','[ERROR] start -> bootingBot -> runIndicatorBot -> onInitializeReady -> whenStartFinishes -> Bot Id = Masters.Candles-Volumes.Multi-Period-Market'] @ Masters-Candles-Volumes-Multi-Period-Market
Task Server                                              Root : [ERROR] start -> bootingBot -> runIndicatorBot -> onInitializeReady -> whenStartFinishes -> Bot execution finished with errors. Please check the logs.
2020-06-14T06:08:16.793Z              Binance   BTC/USDT                Candles-Volumes             Multi-Period-Daily      Main Loop     #        1
2020-06-14T06:08:24.281Z              Binance   BTC/USDT             Bollinger-Channels            Multi-Period-Market      Main Loop     #     5647
2020-06-14T06:08:31.889Z              Binance   BTC/USDT                            EMA            Multi-Period-Market      Main Loop     #     3955
2020-06-14T06:08:36.992Z              Binance   BTC/USDT                            RSI            M

## Attach a video reproducing the issue

N/A

## Attach relevant log files and error screenshots

[Archive.zip](https://github.com/Superalgos/Superalgos/files/4776109/Archive.zip)

## Attach you custom workspace if any

Attach custom workspace here.

**Comment by Luis-Fernando-Molina** [comment]
Trading engine completely re written in beta6. Plase switch to this new version.
