### ISSUE TITLE
weird 10 conditions not allowed on Trigger On Node on Trading System

### ISSUE THREAD

**Issue by 5argh** [Superalgos/Superalgos#3132]
## Before you open an issue

There are two requirements to open an issue:

1. You must first follow the [Troubleshooting Guide](https://docs.superalgos.org/suite-how-to-troubleshoot-an-issue.html)

2. If your issue hasn't been resolved by following the Troubleshooting Guide, then follow the guide on [How to Report an Issue](https://docs.superalgos.org/suite-how-to-report-an-issue.html).

## Context

*Complete and adjust the contents leaving the information that fits your case and deleting the information that doesn't.*

**Operating System:** Windows

**Software version:** today's master branch 

**Workspace version:** default Workspace.json (Getting Started Guide) | Simple Workspace.json | Workspace - Binance - WHB - BBTB.json | My custom workspace 

**Reproducible:** the issue may | may not be reproduced.

### 1. Explain what the problem seems to be.

Log shows error and session finishes unexpectedly when there is more than 9 conditions on the "Trigger On Node" inside the trading system

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

- Create a fresh workspace using any workspace plug-in (ex. Blank WorkSpace , Getting Started)
- Create a new Trading system and add 9 conditions on the trigger on node with "false" in it
- Install BTC/USDT market and configure a backtesting session to be done
- Run backtest session and works as it is expected
- Add a 10th condition and run backtest session again
- get error on console log and backtest session finishes

### 4. Explain what is the result you expect from your actions.

A succesfull backtest

### 5. Explain what happens instead of the expected results.

Log Error

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

Error on low frequency botsd

## Attach relevant log files and error screenshots
![hafsdhasdjhnds](https://user-images.githubusercontent.com/84871267/146104578-c8bd427d-68fd-4216-8fc8-52dd4125d01a.PNG)

Attach logs here.

**Comment by jfriaspt** [comment]
I have similar error when try to run Whb backtesting. At first tought that was missing some data mining bot. But installed everything needed to run Whb. Even tryed the Weak-hands-Buster-v2-Demo workspace, but still the same errors. Any clue to solve this?

Error Stack
The following is the Error Stack of the Exception that occurred at the LF Trading Bot:
errorStack
 TypeError: Cannot read properties of undefined (reading 'movingAverage')
    at eval (eval at evalCondition (/home/pi/Superalgos/Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/TradingSystem.js:327:21), :1:56)
    at evalCondition (/home/pi/Superalgos/Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/TradingSystem.js:327:21)
    at evalNode (/home/pi/Superalgos/Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/TradingSystem.js:251:17)
    at evalNode (/home/pi/Superalgos/Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/TradingSystem.js:297:33)
    at evalNode (/home/pi/Superalgos/Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/TradingSystem.js:297:33)
    at evalNode (/home/pi/Superalgos/Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/TradingSystem.js:287:33)
    at evalNode (/home/pi/Superalgos/Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/TradingSystem.js:287:33)
    at evalNode (/home/pi/Superalgos/Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/TradingSystem.js:297:33)
    at Object.tradingSystem.evalConditions (/home/pi/Superalgos/Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/TradingSystem.js:70:13)
    at checkTriggerOn (/home/pi/Superalgos/Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/TradingStages.js:118:31)
    at Object.runTriggerStage (/home/pi/Superalgos/Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/TradingStages.js:104:9)
    at Object.run (/home/pi/Superalgos/Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/TradingSystem.js:206:39)
    at runCycle (/home/pi/Superalgos/Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/TradingSimulation.js:233:53)
    at Object.runSimulation (/home/pi/Superalgos/Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/TradingSimulation.js:175:23)
    at Object.start (/home/pi/Superalgos/Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/TradingOutput.js:47:49)
    at async outputManagement (/home/pi/Superalgos/Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/TradingProcess.js:263:17)
