### ISSUE TITLE
Error running backtest after following tutorial

### ISSUE THREAD

**Issue by CarnivalBen** [Superalgos/Superalgos#315]
Using a clean checkout of the **develop** branch.

Workspace: Plugin->Trading-System-Design-Tutorials

Followed all tutorial steps up to: 3. Testing a Trading Idea - The Trigger Stage > Second Backtest > Ready. Set. Go!

When I run the second backtest as mentioned in the tutorial, after setting the condition on the Trigger Stage > Take Position Event, I see the following errors in the console:

```
*********** ['2021-01-04T16:35:39.852Z',209,'Trading System','[ERROR] runExecution -> err = TypeError: Cannot read property 'openStage' of undefined
    at runWhenStatusIsOpening (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingStages.js:282:93)
    at Object.runOpenStage (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingStages.js:260:9)
    at Object.run (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingSystem.js:148:45)
    at runCycle (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingSimulation.js:194:53)
    at Object.runSimulation (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingSimulation.js:150:23)
    at Object.start (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingOutput.js:74:49)
    at async generateOutput (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingProcess.js:604:17)
    at async Object.start (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingProcess.js:133:21)'] @ Masters-[object Object]-Trading
*********** ['2021-01-04T16:35:39.867Z',216,'Trading System','[ERROR] runExecution -> err = TypeError: Cannot read property 'openStage' of undefined
    at runWhenStatusIsOpening (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingStages.js:282:93)
    at Object.runOpenStage (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingStages.js:260:9)
    at Object.run (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingSystem.js:148:45)
    at runCycle (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingSimulation.js:194:53)
    at Object.runSimulation (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingSimulation.js:174:23)
    at async Object.start (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingOutput.js:74:13)
    at async generateOutput (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingProcess.js:604:17)
    at async Object.start (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingProcess.js:133:21)'] @ Masters-[object Object]-Trading
2021-01-04T16:35:39.874Z              Binance   BTC/USDT              Masters                  Low-Frequency                        Trading      Internal Loop #        2                     2020-01-02     0.36 %
*********** ['2021-01-04T16:35:39.879Z',227,'Trading System','[ERROR] runExecution -> err = TypeError: Cannot read property 'openStage' of undefined
    at runWhenStatusIsOpening (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingStages.js:282:93)
    at Object.runOpenStage (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingStages.js:260:9)
    at Object.run (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingSystem.js:148:45)
    at runCycle (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingSimulation.js:194:53)
    at Object.runSimulation (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingSimulation.js:150:23)
    at async Object.start (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingOutput.js:74:13)
    at async generateOutput (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingProcess.js:604:17)
    at async Object.start (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingProcess.js:133:21)'] @ Masters-[object Object]-Trading
*********** ['2021-01-04T16:35:39.886Z',234,'Trading System','[ERROR] runExecution -> err = TypeError: Cannot read property 'openStage' of undefined
    at runWhenStatusIsOpening (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingStages.js:282:93)
    at Object.runOpenStage (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingStages.js:260:9)
    at Object.run (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingSystem.js:148:45)
    at runCycle (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingSimulation.js:194:53)
    at Object.runSimulation (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingSimulation.js:174:23)
    at async Object.start (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingOutput.js:74:13)
    at async generateOutput (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingProcess.js:604:17)
    at async Object.start (C:\github\home\superalgos\develop\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingProcess.js:133:21)'] @ Masters-[object Object]-Trading
```

It looks like the same error is repeated for every 1H candle that is processed by the backtest.

**Comment by julian-molina** [comment]
Do not worry: Those errors are part of the tutorial and are discussed in the section following where you left of. Keep going and you'll see!

**Comment by julian-molina** [comment]
@Luis-Fernando-Molina found a bug and fixed it. Thanks for reporting it! Let us know if it works for you...

**Comment by CarnivalBen** [comment]
Yep, fixed and working. Thanks.
