### ISSUE TITLE
'Resume'-button?

### ISSUE THREAD

**Issue by cozed-gh** [Superalgos/Superalgos#683]
**RELATED TO: Backtesting // Run Request is stuck bug #477; opened on 26 Jan by 9808us**

## Before you open an issue

There are two requirements to open an issue:

1. You must first follow the [Troubleshooting Guide](https://docs.superalgos.org/suite-how-to-troubleshoot-an-issue.html)

2. If your issue hasn't been resolved by following the Troubleshooting Guide, then follow the guide on [How to Report an Issue](https://docs.superalgos.org/suite-how-to-report-an-issue.html).

## Context

*Complete and adjust the contents leaving the information that fits your case and deleting the information that doesn't.*

**Operating System:** Windows | MacOs | Linux | Other (include the version on either case)

Windows

**Software version:** today's master branch | today's develop branch 

Today's develop

**Workspace version:** default Workspace.json (Getting Started Guide) | Simple Workspace.json | Workspace - Binance - WHB - BBTB.json | My custom workspace 

Getting Started

**Reproducible:** the issue may | may not be reproduced.

May be reproduced

### 1. Explain what the problem seems to be.

When using the 'Resume' button for backtesting, it doesn't see the proper websocket data.

### 2. Clearly explain what you wish to accomplish.

Run a backtest using 'Resume', after accidentaly clicked 'Run' before starting Trading Processes. Then start the Trading Processes and Run the Backtest.

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

I accidentaly clicked 'Run' backtest before starting the Trading Processes. Started the Trading Processes afterwards and noticed that 'Run' backtest was unavailable, but 'Resume' was available. Clicked 'Resume' and expected the backtest to start.

_Solution might be that 'Run' produces an error and 'resets' in the Trading Processes aren't started._

### 4. Explain what is the result you expect from your actions.

I expected that the Backtest would 'Resume' and start running.

### 5. Explain what happens instead of the expected results.

I get an error code that points me to some 'Websocket' issue.

## Attach relevant log files and error screenshots

2021-02-27T23:03:00.699Z        Low-Frequency                        Trading Wai
ting for Backtesting Session My Trading Strategy to be run.
*********** ['2021-02-27T23:03:00.903Z',2,'Trading Session','[ERROR] initialize
-> **onSessionResume** -> err = TypeError: Cannot read property 'type' of undefined
    at Object.onSessionResume [as callBack] (D:\Superalgos-develop-B9\Superalgos
\Projects\Superalgos\TS\Bot-Modules\Trading-Bot\TradingSession.js:189:134)
    at **WebSocket.WEB_SOCKETS_CLIENT**.onmessage (D:\Superalgos-develop-B9\Superalg
os\Projects\Superalgos\TS\Task-Modules\EventServerClient.js:84:37)
    at WebSocket.onMessage (D:\Superalgos-develop-B9\Superalgos\Projects\Superal
gos\TS\Task-Modules\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (D:\Superalgos-develop-B9\Superalgos\Projects\
Superalgos\TS\Task-Modules\node_modules\ws\lib\websocket.js:825:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (D:\Superalgos-develop-B9\Superalgos\Projects\Supera
lgos\TS\Task-Modules\node_modules\ws\lib\receiver.js:437:14)
    at Receiver.getData (D:\Superalgos-develop-B9\Superalgos\Projects\Superalgos
\TS\Task-Modules\node_modules\ws\lib\receiver.js:367:17)
    at Receiver.startLoop (D:\Superalgos-develop-B9\Superalgos\Projects\Superalg
os\TS\Task-Modules\node_modules\ws\lib\receiver.js:143:22)
    at Receiver._write (D:\Superalgos-develop-B9\Superalgos\Projects\Superalgos\
TS\Task-Modules\node_modules\ws\lib\receiver.js:78:10)'] @ Masters-Low-Frequency
-Trading
2021-02-27T23:03:05.713Z              Binance   BTC/USDT              Masters
               Low-Frequency                        Trading          Main Loop #
        3
*********** ['2021-02-27T23:03:14.311Z',94,'Trading Process','[ERROR] start -> U
nhandled Exception. Will Abort this process. err = TypeError: Cannot read proper
ty '**tradingParameters**' of undefined
    at Object.start (D:\Superalgos-develop-B9\Superalgos\Projects\Superalgos\TS\
Bot-Modules\Trading-Bot\Low-Frequency-Trading\TradingProcess.js:36:130)
    at startProcessFramework (D:\Superalgos-develop-B9\Superalgos\Projects\Super
algos\TS\Bot-Modules\Trading-Bot\SingleMarketTradingBot.js:340:46)
    at onInizialized (D:\Superalgos-develop-B9\Superalgos\Projects\Superalgos\TS
\Bot-Modules\Trading-Bot\SingleMarketTradingBot.js:285:53)
    at Object.initialize (D:\Superalgos-develop-B9\Superalgos\Projects\Superalgo
s\TS\Process-Modules\DataDependencies.js:173:17)
    at initializeDataDependencies (D:\Superalgos-develop-B9\Superalgos\Projects\
Superalgos\TS\Bot-Modules\Trading-Bot\SingleMarketTradingBot.js:274:46)
    at onInizialized (D:\Superalgos-develop-B9\Superalgos\Projects\Superalgos\TS
\Bot-Modules\Trading-Bot\SingleMarketTradingBot.js:229:45)
    at addReport (D:\Superalgos-develop-B9\Superalgos\Projects\Superalgos\TS\Pro
cess-Modules\StatusDependencies.js:144:29)
    at onLoad (D:\Superalgos-develop-B9\Superalgos\Projects\Superalgos\TS\Proces
s-Modules\StatusDependencies.js:91:33)
    at onFileReceived (D:\Superalgos-develop-B9\Superalgos\Projects\Superalgos\TS\Process-Modules\StatusReport.js:347:21)
    at Timeout.retry [as _onTimeout] (D:\Superalgos-develop-B9\Superalgos\Projects\Superalgos\TS\Task-Modules\FileStorage.js:214:25)'] @ Masters-Low-Frequency-Trading
*********** ['2021-02-27T23:03:14.312Z',95,'Single Market Trading Bot','[ERROR] run -> loop -> startProcessFramework -> onFinished -> Operation Failed. Aborting the process.'] @ Masters-Low-Frequency-Trading
*********** ['2021-02-27T23:03:14.316Z',3,'Process Instance','[ERROR] start -> onInitializeReady -> whenStartFinishes -> err = Operation Failed'] @ Masters-Low-Frequency-Trading
*********** ['2021-02-27T23:03:14.316Z',4,'Process Instance','[ERROR] start -> onInitializeReady -> whenStartFinishes -> Execution will be stopped. '] @ Masters-Low-Frequency-Trading
*********** ['2021-02-27T23:03:14.317Z',5,'Process Instance','[ERROR] start -> onInitializeReady -> whenStartFinishes -> Bye.'] @ Masters-Low-Frequency-Trading
*********** ['2021-02-27T23:03:14.318Z',6,'Process Instance','[ERROR] start -> onInitializeReady -> whenStartFinishes -> Bot Id = Masters.Low-Frequency.Trading'] @ Masters-Low-Frequency-Trading
Task Server                                              Process Instance : [ERROR] start -> onInitializeReady -> whenStartFinishes -> Bot execution was aborted.

**Comment by Smidy13** [comment]
I think this issue can probably be closed. There are definite issues with the "Resume" command. But this is probably best captured under #802. Therefore this can probably be closed and we will investigate under #802.
