### ISSUE TITLE
Fails to run on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by cyberkryption** [Superalgos/Superalgos#794]
Issue: Superalgos will not run on Ubuntu18.04 LTS - fails to start the client.

### How to Reproduce ###
1. Fresh install Ubuntu 18.04
2. sudo apt-get-y update
3. sudo apt-get upgrade
4. sudo apt-get install build-essential gcc make
5. curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.35.3/install.sh -o install_nvm.sh
6. bash install_nvm.sh
7.  source ~/.profile
8.  nvm install 10.24.1
9. node -v 
```
node -v
v10.24.1
npm -v
6.14.12
 ```
10. git clone https://github.com/cyberkryption/Superalgos
11. cd Superalgos
12. node run

**Truncated Output**
```
Contribution Management ..................................... This will allow us to manage contributions at scale, and distribute the SA token more efficiently at each release.
Infraestructure to sensor any API  .......................... This will allow us to fetch data from any API, turn it into indicators and plot it.
Usage of ML Predictions at Trading Systems .................. This will enable a new kind of Bot that can learn from data mined. Later that knowledge can be used at trading strategies.
Ethereum Integration ........................................ This will allow mining data from an Ethereum network node, create indicators with it, an use it on strategies.

[ERROR] Client -> client-> uncaughtException -> err.message = spawn xdg-open ENOENT
[ERROR] Client -> client-> uncaughtException -> err.stack = Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[ERROR] Client -> client-> uncaughtException -> err = Error: spawn xdg-open ENOENT

```

**Investigations**
1.Googled error and found this stackoverflow post relating to the error see - https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js
2. Modified client.js (after reading code to see what was being called) to have extra code to see more detailed error as shown below
**Trunacted Code**
```
(function() {
    var childProcess = require("child_process");
    var oldSpawn = childProcess.spawn;
    function mySpawn() {
        console.log( process.env.PATH );
        console.log( env.PATH );
        console.log('spawn called');
        console.log(arguments);
        var result = oldSpawn.apply(this, arguments);
        return result;
    }
    childProcess.spawn = mySpawn;
})();
/* Load Environment Variables */
let ENVIRONMENT = require('../Environment.js');
let ENVIRONMENT_MODULE = ENVIRONMENT.newEnvironment()
global.env = ENVIRONMENT_MODULE

```
3. Reran node run and got the following output

```
What's next? At the development pipeline we have:

Contribution Management ..................................... This will allow us to manage contributions at scale, and distribute the SA token more efficiently at each release.
Infraestructure to sensor any API  .......................... This will allow us to fetch data from any API, turn it into indicators and plot it.
Usage of ML Predictions at Trading Systems .................. This will enable a new kind of Bot that can learn from data mined. Later that knowledge can be used at trading strategies.
Ethereum Integration ........................................ This will allow mining data from an Ethereum network node, create indicators with it, an use it on strategies.

**PATH is /home/cyberkryption/.nvm/versions/node/v10.24.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin**
undefined
spawn called
[Arguments] {
  '0': 'xdg-open',
  '1': [ 'http://localhost:34248' ],
  '2': { stdio: 'ignore', detached: true } }
[ERROR] Client -> client-> uncaughtException -> err.message = spawn xdg-open ENOENT
[ERROR] Client -> client-> uncaughtException -> err.stack = Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[ERROR] Client -> client-> uncaughtException -> err = Error: spawn xdg-open ENOENT

```

To me it looks like the client is failing to attach to the server, but it could be a path issue.

Any help appreciated

Cyberkrpyion

**Comment by harrellbm** [comment]
I am currently running Superalgos on Ubuntu 20.04 and Node 10.19.0 with no issues.  

From what I see it looks like your node install script is introducing something causing the error. It seems that it installs node as a snap? 

If that's true, I don't think Superalgos is currently set up to be compatible with snap. 

I would try a simple manual install of node and see if that fixes things.

**Comment by cyberkryption** [comment]
Hi Ben,

I did not use snap to install node.

I simply used nvm to install it on a fresh ubuntu. I will try diwngrading
node and see if that solves it.

Cyberkryption

**Comment by harrellbm** [comment]
If that does not work, I would recommend using the following commands for a reinstall (as found in the Readme).

'''
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
'''

'''
sudo apt-get install -y nodejs
'''
